version: '1.0'
services:
  ros:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    privileged: true # docker run --privileged
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros-kinetic
    restart: always
    volumes:
      - ./:/ros_ws