version: '1.0'
services:
  ros:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros-kinetic
    restart: always
    volumes:
      - ./:/ros_ws
    devices:
      - /dev/vport0p1:/dev/vport0p1